# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: 906bc906
email: 906bc906@gmail.com
name: 906bc906
description: >- # this means to ignore newlines until "baseurl:"
  Second, and Public brain of 906bc906
# keywords: [Your keywords]
baseurl: '/jekyll-blog' # the subpath of your site, e.g. /`blog
url: 'https://906bc906.github.io' # the base hostname & protocol for your site, e.g. http://example.com
domain: '906bc906' # the domain name for your site, e.g. example.com
language: ko
# Supported languages list:
# en: English
# de: Deutsche (German)
# es: Español (Spanish)
# fr: Français (French)
# ja: 日本語 (Japanese)
# pt: Português (Portuguese)
# zh-cn: 简体中文 (Simplified Chinese)
# zh-tw: 繁體中文 (Traditional Chinese)
# ko : 한국어 (Korean)

analytics: # the Google Analytics property ID, e.g. UA-XXXXX-Y

comments: true # enable comments
disqus: # disqus account

mathjax: true # Math support
diagram: true # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

include: ["_pages/note"]
exclude: ["_pages/template"]

collections:
  pages:
    ralative_directory: "_pages/note"
    output: true
    permalink: /:collection/:path.md

timezone: Asia/Seoul

defaults:
  -
    scope:
      path: "_pages"
    values:
      layout: "post"
      render_with_liquid: false
      toc: true

feed:
  collections:
    - pages

toc:
  min_level: 2
  max_level: 4
  ordered_list: true

# Build settings
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
